### ISSUE TITLE
Not working with PoB Community 1.4.170.12

### ISSUE THREAD

**Issue by Nightblade** [coldino/pob_wrapper#2]
Hi!  Looks like the latest PoBC has broken something :-(
The first thing I noticed is that `get_builds_dir()` seems to be getting a *relative* path to the builds dir now:

```
C:\Users\Nighty\Downloads\pob_wrapper-master>python example.py
LUA: Started

POB Builds: ./Path of Building/Builds/

Loading build:
{'buildName': 'ED 03',
 'char': {'ascendClassName': 'Scion', 'className': 'Scion', 'level': 1},
 'file': {'path': './Path of Building/Builds/\\ED 03.xml', 'subpath': '\\'}}

Updating build:
Traceback (most recent call last):
  File "example.py", line 63, in <module>
    pob = run()
  File "example.py", line 44, in run
    pob.update_build()
  File "C:\Users\Nighty\Downloads\pob_wrapper-master\pob_wrapper\pob.py", line 96, in update_build
    result = self._send(f'updateBuild()')
  File "C:\Users\Nighty\Downloads\pob_wrapper-master\pob_wrapper\pob.py", line 148, in _send
    raise ExternalError(result)
pob_wrapper.process_wrapper.ExternalError: {'status': 'run_fail', 'error': "...ty\\Downloads\\pob_wrapper-master\\pob_wrapper\\data\\cli.lua:59: attempt to index local 'socketGroup' (a nil value)"}
```

Feeding it the correct path does this:
```
C:\Users\Nighty\Downloads\pob_wrapper-master>python example.py
LUA: Started

POB Builds: ./Path of Building/Builds/

Loading build:
{'buildName': 'ED 03',
 'char': {'ascendClassName': 'Trickster', 'className': 'Shadow', 'level': 83},
 'file': {'path': 'C:\\Users\\Nighty\\Documents\\Path of Building\\Builds\\ED '
                  '03.xml',
          'subpath': 'Path of Building\\Builds\\'}}

Updating build:
Traceback (most recent call last):
  File "example.py", line 63, in <module>
    pob = run()
  File "example.py", line 44, in run
    pob.update_build()
  File "C:\Users\Nighty\Downloads\pob_wrapper-master\pob_wrapper\pob.py", line 96, in update_build
    result = self._send(f'updateBuild()')
  File "C:\Users\Nighty\Downloads\pob_wrapper-master\pob_wrapper\pob.py", line 148, in _send
    raise ExternalError(result)
pob_wrapper.process_wrapper.ExternalError: {'status': 'run_fail', 'error': '...ty\\Downloads\\pob_wrapper-master\\pob_wrapper\\data\\cli.lua:72: Account name not configured'}
```

For completeness, these are the lines I changed in `example.py` to make it work on my system:
```python
    ...
    pob_install = r'C:\Program Files (x86)\Path of Building Community'
    pob_path = r'C:\Program Files (x86)\Path of Building Community'
    ...
    pob.load_build(r'C:\Users\Nighty\Documents\Path of Building\Builds\ED 03.xml')
    ...
```

**Comment by coldino** [comment]
Thanks for this. This is actually the same issue we're seeing with the community edition with PoB Item Tester too, so we're actively trying to find a good workaround.

It's worth nothing that it seems to behave differently between installed and portable editions, but not sure why.

**Comment by coldino** [comment]
Testing on this fix is looking good so far, but please let me know how it goes for you.
