### ISSUE TITLE
ModuleNotFoundError: No module named 'pob_wrapper'

### ISSUE THREAD

**Issue by grummble-ai** [coldino/pob_wrapper#5]
When I try to run the example, I get the above error. Any idea how to solve this? The following functions throws the error: 
```
def get_provider(moduleOrReq):
                """Return an IResourceProvider for the named module or requirement"""
                if isinstance(moduleOrReq, Requirement):
                    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
                try:
                    module = sys.modules[moduleOrReq]
                except KeyError:
                    __import__(moduleOrReq)
                    module = sys.modules[moduleOrReq]
                loader = getattr(module, '__loader__', None)
                return _find_adapter(_provider_factories, loader)(module) 
```

**Comment by coldino** [comment]
Not sure where that function comes from, but it isn't this project.

What are you trying to do?

**Comment by grummble-ai** [comment]
It is:

`Traceback (most recent call last):
  File "C:\Users\...\PycharmProjects\PoEBuildTradeSearches\example.py", line 63, in <module>
    pob = run()
  File "C:\Users\...\PycharmProjects\PoEBuildTradeSearches\example.py", line 34, in run
    pob = PathOfBuilding(pob_path, pob_install)
  File "C:\Users\...\PycharmProjects\PoEBuildTradeSearches\tools\pob_wrapper\pob.py", line 82, in __init__
    data_dir = pkg_resources.resource_filename('pob_wrapper', 'data')
  File "C:\Users\...\PycharmProjects\PoEBuildTradeSearches-Venv\lib\site-packages\pkg_resources\__init__.py", line 1130, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "C:\Users\...\PycharmProjects\PoEBuildTradeSearches-Venv\lib\site-packages\pkg_resources\__init__.py", line 346, in get_provider
    __import__(moduleOrReq)
ModuleNotFoundError: No module named 'pob_wrapper'
`

**Comment by grummble-ai** [comment]
Nevermind, I have solved the issue, which was caused by making the pob_wrapper folder a subfolder. It seems that there are absolute paths in the code that do not allow this.
